make:
		cd ../uchardet && cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_BINARY=OFF && make
install:
		# The gem will load the library from where it was built.
clean:
		# Any files will be cleaned up when the gem is uninstalled.
